version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gomod:
        dependency-type: "production"
      gomod-dev:
        dependency-type: "development"
    assignees:
      - "Valentin-Kaiser"
    reviewers:
      - "Valentin-Kaiser"