// Package xrpc serves protobuf services over JSON-RPC 2.0, an XML flavour of
// JSON-RPC 2.0, and gRPC from a single registration.
//
// Services are implemented against the interfaces generated by protoc-gen-jrpc
// and registered with Register. Mount the result with web.Server.WithXRPC or use
// it directly as an http.Handler.
//
// Protocols, selected by Content-Type:
//   - application/json: JSON-RPC 2.0 over HTTP POST, including batches and notifications.
//   - application/xml:  the same request/response model encoded as XML.
//   - application/grpc: native gRPC over HTTP/2.
//
// JSON and XML messages use protobuf field numbers instead of field names
// (JSON {"1":"a"}, XML <_1>a</_1>), which keeps payloads small and makes field
// renames and deprecations wire compatible. Decoders also accept field names.
// Use WithFieldNames to emit names.
//
// Streaming methods are available over gRPC and over WebSocket (GET with an
// Upgrade header, sub-protocol xrpc.json or xrpc.xml). On a WebSocket the
// client sends an ordinary request with an id; messages flow as notifications
// "xrpc.message" with params {"id": <request id>, "data": <message>} in both
// directions; the client ends its side with "xrpc.close" or aborts with
// "xrpc.cancel"; the server ends the stream with the response to the request
// (null for server and bidirectional streams, the result for client streams).
// The request params of a server streaming method carry the single request
// message; for client and bidirectional streams they are ignored.
package xrpc

import (
	"context"
	"errors"
	"io"
	"mime"
	"net/http"
	"reflect"
	"strconv"
	"strings"
	"sync"

	"github.com/gorilla/websocket"
	"github.com/valentin-kaiser/go-core/apperror"
	"github.com/valentin-kaiser/go-core/interruption"
	"github.com/valentin-kaiser/go-core/logging"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/reflect/protoreflect"
)

var (
	logger             = logging.GetPackageLogger("xrpc")
	errMissingStreamID = apperror.NewError("missing stream id")
)

const defaultMaxBody = 4 << 20

// Server is a service implementation; Descriptor is provided by the generated code.
type Server interface {
	Descriptor() protoreflect.FileDescriptor
}

// Service dispatches calls to the registered service implementations.
// Configure it before serving; the With* methods are not safe for concurrent use.
type Service struct {
	methods  map[string]*method
	list     []*method
	fold     bool
	codec    codec
	namesHdr string
	namesQry string
	maxBody  int64
	upgrader websocket.Upgrader
	grpcOpts []grpc.ServerOption
	grpcOnce sync.Once
	grpcSrv  *grpc.Server
}

// Register creates a Service from one or more implementations. Methods are
// addressed as "Service.Method", "pkg.Service.Method" or "pkg.Service/Method".
func Register(servers ...Server) *Service {
	s := &Service{
		methods: make(map[string]*method),
		maxBody: defaultMaxBody,
	}

	for _, srv := range servers {
		sv := reflect.ValueOf(srv)
		services := srv.Descriptor().Services()
		for i := 0; i < services.Len(); i++ {
			sd := services.Get(i)
			for j := 0; j < sd.Methods().Len(); j++ {
				md := sd.Methods().Get(j)
				fn := sv.MethodByName(string(md.Name()))
				if !fn.IsValid() {
					continue
				}

				m, err := bind(fn, md)
				if err != nil {
					logger.Error().Err(err).Field("method", string(sd.FullName())+"/"+string(md.Name())).Msg("skipping method with invalid signature")
					continue
				}
				m.service = string(sd.Name())
				m.full = string(sd.FullName())

				if _, dup := s.methods[m.service+"."+m.name]; dup {
					continue
				}
				for _, key := range []string{m.service + "." + m.name, m.full + "." + m.name, m.full + "/" + m.name} {
					s.methods[key] = m
				}
				s.list = append(s.list, m)
			}
		}
	}
	return s
}

// WithFieldNames makes JSON and XML output use field names instead of field numbers.
func (s *Service) WithFieldNames() *Service {
	s.codec.names = true
	return s
}

// WithFieldNamesHeader lets a request header choose the encoding of its response:
// a boolean value selects field names (true) or field numbers (false), overriding
// the service default. On a WebSocket the header of the handshake applies to the whole connection.
func (s *Service) WithFieldNamesHeader(name string) *Service {
	s.namesHdr = http.CanonicalHeaderKey(name)
	return s
}

// WithFieldNamesQuery lets the query string of a WebSocket handshake choose the encoding like
// WithFieldNamesHeader does, for clients that cannot set handshake headers (browsers).
// A configured header takes precedence.
func (s *Service) WithFieldNamesQuery(param string) *Service {
	s.namesQry = param
	return s
}

func (s *Service) codecFor(w http.ResponseWriter, r *http.Request) codec {
	c := s.codec
	if s.namesHdr != "" {
		w.Header().Add("Vary", s.namesHdr)
		if v := r.Header.Get(s.namesHdr); v != "" {
			if names, err := strconv.ParseBool(v); err == nil {
				return codec{names: names}
			}
		}
	}
	if s.namesQry != "" && websocket.IsWebSocketUpgrade(r) {
		if names, err := strconv.ParseBool(r.URL.Query().Get(s.namesQry)); err == nil {
			return codec{names: names}
		}
	}
	return c
}

// WithMaxBodySize limits the size of request bodies and WebSocket messages. The default is 4 MiB.
func (s *Service) WithMaxBodySize(n int64) *Service {
	s.maxBody = n
	return s
}

// WithCheckOrigin sets the WebSocket origin check. By default only same-origin browser requests are accepted.
func (s *Service) WithCheckOrigin(check func(*http.Request) bool) *Service {
	s.upgrader.CheckOrigin = check
	return s
}

// WithGRPCOptions sets options for the embedded gRPC server, e.g. interceptors.
func (s *Service) WithGRPCOptions(opts ...grpc.ServerOption) *Service {
	s.grpcOpts = append(s.grpcOpts, opts...)
	return s
}

// WithCaseInsensitiveMethods makes method names match regardless of case.
func (s *Service) WithCaseInsensitiveMethods() *Service {
	s.fold = true
	return s
}

func (s *Service) find(name string) *method {
	if m := s.methods[name]; m != nil || !s.fold {
		return m
	}
	for key, m := range s.methods {
		if strings.EqualFold(key, name) {
			return m
		}
	}
	return nil
}

// Handles reports whether the service has a handler for the given service and method name.
func (s *Service) Handles(service, method string) bool {
	return s.find(service+"."+method) != nil || s.find(service+"/"+method) != nil
}

// Paths returns the gRPC request paths ("/pkg.Service/Method") served by this service.
func (s *Service) Paths() []string {
	paths := make([]string, 0, len(s.list))
	for _, m := range s.list {
		paths = append(paths, "/"+m.full+"/"+m.name)
	}
	return paths
}

type contextKey int

const (
	keyRequest contextKey = iota
	keyWriter
	keyConn
	keyProtocol
	keyStatus
)

type statusBox struct{ code int }

// SetStatus lets a handler choose the HTTP status of the response, e.g. 401 for a failed authentication.
// It only applies to single (non-batch) HTTP calls; for other calls it does nothing and returns false.
func SetStatus(ctx context.Context, code int) bool {
	b, ok := ctx.Value(keyStatus).(*statusBox)
	if ok {
		b.code = code
	}
	return ok
}

// WithHTTPContext adds the HTTP request and response writer to ctx.
func WithHTTPContext(ctx context.Context, w http.ResponseWriter, r *http.Request) context.Context {
	ctx = context.WithValue(ctx, keyWriter, w)
	return context.WithValue(ctx, keyRequest, r)
}

// WithWebSocketContext adds the HTTP upgrade request, response writer and WebSocket connection to ctx.
func WithWebSocketContext(ctx context.Context, w http.ResponseWriter, r *http.Request, conn *websocket.Conn) context.Context {
	return context.WithValue(WithHTTPContext(ctx, w, r), keyConn, conn)
}

// GetRequest returns the HTTP request that started the call.
func GetRequest(ctx context.Context) (*http.Request, bool) {
	r, ok := ctx.Value(keyRequest).(*http.Request)
	return r, ok
}

// GetResponseWriter returns the HTTP response writer of the call. It is unavailable on WebSocket and gRPC streams after the upgrade.
func GetResponseWriter(ctx context.Context) (http.ResponseWriter, bool) {
	w, ok := ctx.Value(keyWriter).(http.ResponseWriter)
	return w, ok
}

// GetWebSocketConn returns the WebSocket connection of the call.
func GetWebSocketConn(ctx context.Context) (*websocket.Conn, bool) {
	c, ok := ctx.Value(keyConn).(*websocket.Conn)
	return c, ok
}

// GetProtocol returns the wire protocol of the call.
func GetProtocol(ctx context.Context) (Protocol, bool) {
	p, ok := ctx.Value(keyProtocol).(Protocol)
	return p, ok
}

func withProtocol(ctx context.Context, p Protocol) context.Context {
	return context.WithValue(ctx, keyProtocol, p)
}

func mediaType(r *http.Request) string {
	mt, _, err := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if err != nil {
		return ""
	}
	return mt
}

func isGRPC(r *http.Request) bool {
	return r.ProtoMajor == 2 && strings.HasPrefix(mediaType(r), "application/grpc")
}

// ServeHTTP selects the protocol from the request and serves it.
func (s *Service) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	defer interruption.Catch()

	switch {
	case websocket.IsWebSocketUpgrade(r):
		s.serveWS(w, r)
	case r.Method == http.MethodOptions:
		w.WriteHeader(http.StatusNoContent)
	case isGRPC(r):
		s.serveGRPC(w, r)
	case r.Method != http.MethodPost:
		w.Header().Set("Allow", "POST, OPTIONS")
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	default:
		switch mediaType(r) {
		case "application/json", "application/json-rpc", "application/jsonrequest":
			s.serveHTTP(w, r, newWire(ProtocolJSON, s.codecFor(w, r)))
		case "application/xml", "text/xml":
			s.serveHTTP(w, r, newWire(ProtocolXML, s.codecFor(w, r)))
		default:
			w.Header().Set("Accept-Post", "application/json, application/xml, application/grpc")
			http.Error(w, "unsupported content type", http.StatusUnsupportedMediaType)
		}
	}
}

func (s *Service) serveHTTP(w http.ResponseWriter, r *http.Request, wr wire) {
	body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, s.maxBody))
	if err != nil {
		var tooLarge *http.MaxBytesError
		if errors.As(err, &tooLarge) {
			http.Error(w, "request body too large", http.StatusRequestEntityTooLarge)
			return
		}
		http.Error(w, "failed to read request body", http.StatusBadRequest)
		return
	}

	ctx := withProtocol(WithHTTPContext(r.Context(), w, r), wr.protocol())
	status := &statusBox{}
	ctx = context.WithValue(ctx, keyStatus, status)
	envs, batch, perr := wr.parse(body)

	var replies []*reply
	if perr != nil {
		replies, batch = []*reply{{id: rpcID{set: true, null: true}, err: perr}}, false
	} else {
		replies = s.process(ctx, envs)
	}
	if len(replies) == 0 {
		w.WriteHeader(http.StatusNoContent)
		return
	}

	out, err := wr.encodeReplies(replies, batch)
	if err != nil {
		logger.Error().Err(err).Msg("failed to encode response")
		http.Error(w, "failed to encode response", http.StatusInternalServerError)
		return
	}

	code := http.StatusOK
	if !batch && replies[0].err != nil {
		code = httpStatus(replies[0].err)
	}
	if !batch && status.code != 0 {
		code = status.code
	}
	w.Header().Set("Content-Type", wr.contentType())
	w.WriteHeader(code)
	if _, err := w.Write(out); err != nil {
		logger.Error().Err(err).Msg("failed to write response")
	}
}

// process handles unary calls; notifications produce no reply.
func (s *Service) process(ctx context.Context, envs []*envelope) []*reply {
	replies := make([]*reply, 0, len(envs))
	for _, e := range envs {
		if r := s.handle(ctx, e); r != nil {
			replies = append(replies, r)
		}
	}
	return replies
}

func (s *Service) handle(ctx context.Context, e *envelope) *reply {
	if e.isResp {
		return &reply{id: rpcID{set: true, null: true}, err: NewError(CodeInvalidRequest, "invalid request")}
	}
	if e.err != nil {
		return &reply{id: e.id, err: e.err}
	}

	notify := !e.id.set
	fail := func(err *Error) *reply {
		if notify {
			return nil
		}
		return &reply{id: e.id, err: err}
	}

	m := s.find(e.method)
	if m == nil {
		return fail(NewError(CodeMethodNotFound, "method not found"))
	}
	if m.kind != kindUnary {
		return fail(NewError(CodeStreamingRequired, "streaming method requires WebSocket or gRPC"))
	}

	in := m.newIn()
	if err := e.bind(in); err != nil {
		return fail(NewError(CodeInvalidParams, "invalid params: "+err.Error()))
	}

	out, err := m.invoke(ctx, in, nil, nil)
	l := logger.Trace()
	if err != nil {
		l = logger.Warn().Err(err)
	}
	l.Field("method", m.full+"/"+m.name).Msg("xrpc method called")

	if err != nil {
		return fail(toError(err))
	}
	if notify {
		return nil
	}
	return &reply{id: e.id, result: out}
}
